### ISSUE TITLE
gg s crashes

### ISSUE THREAD

**Issue by casidiablo** [qw3rtman/gg#13]
``` sh
gg s
branch   | develop
position | up-to-date


/usr/local/lib/node_modules/gitgoodies/lib/gg.js:197
                if (status[4].split(' ')[0] === 'Untracked') {
                              ^
TypeError: Cannot call method 'split' of undefined
    at /usr/local/lib/node_modules/gitgoodies/lib/gg.js:197:19
    at ChildProcess.exithandler (child_process.js:656:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

**Comment by qw3rtman** [comment]
Working on fixing this. See #3. :smile:
