### ISSUE TITLE
(Windows) gg log error

### ISSUE THREAD

**Issue by Semigradsky** [qw3rtman/gg#19]
Typed:
`gg l`

Result:

```
undefined:1
[

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at C:\Users\d.semigradsky\AppData\Roaming\npm\node_modules\gitgoodies\lib\gg
.js:383:18
    at ChildProcess.exithandler (child_process.js:751:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
```

**Comment by Semigradsky** [comment]
`stderr` in `exports.log` function:

```
fatal: Invalid object name 'commit'.
Can't find string terminator '"' anywhere before EOF at -e line 1.
```

**Comment by vincent** [comment]
kind of the same here.

here's the error, and the last `stdout` variable content:

```
{
  "commit": "c21bb0dc1d77a9bd77bfbc99baa5716f1c3227ea",
  "author": "allyouneedisgnu",
  "date": "Tue Dec 2 13:50:23 2014 +0100",
  "message": "Merged-in-itcollection_correctionTests

undefined:5789
  "message": "Merged-in-itcollection_correctionTests
                                                    ^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /usr/local/lib/node_modules/gitgoodies/lib/gg.js:384:18
    at ChildProcess.exithandler (child_process.js:654:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```
