### ISSUE TITLE
Keeps throwing an error!!

### ISSUE THREAD

**Issue by nim23** [qw3rtman/gg#3]
I keep getting an error when running gg s. Tried with node version 0.10.35 and 0.12.0 both running via nvm.

![screen shot 2015-03-05 at 11 41 43](https://cloud.githubusercontent.com/assets/1999331/6504224/d46457bc-c32c-11e4-8886-b87265555bc8.png)

**Comment by wojciechgucik** [comment]
+1
error shows up when you have clean working directory.
logging out status variable shows status[4] is empty string when there is nothing to commit:
[
 'On branch foo-branch',
  'Your branch is up-to-date with \'origin/foo-branch\'.',
  'nothing to commit, working directory clean',
  '' 
]

**Comment by qw3rtman** [comment]
Merged and published to npm. Update with `npm update -g gitgoodies`. Let me know if the issue is fixed.

**Comment by nim23** [comment]
Thanks for the quick fix, it's working all fine now.

**Comment by ch-stuart** [comment]
I'm seeing this issue currently. Just installed gg today.

```
~/code/puppet (nvm: v0.12.0)
$ gg status
branch   | foo
position | up-to-date

~/.nvm/v0.12.0/lib/node_modules/gitgoodies/lib/gg.js:194
                if (status[4].split(' ')[0] === 'Untracked') {
                             ^
TypeError: Cannot read property 'split' of undefined
    at ~/.nvm/v0.12.0/lib/node_modules/gitgoodies/lib/gg.js:194:18
    at ChildProcess.exithandler (child_process.js:735:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)

~/code/puppet (nvm: v0.12.0)
$ git status
On branch foo
Your branch is up-to-date with 'origin/foo'.
nothing to commit, working directory clean
```

Let me know what other information I can provide.

**Comment by heyvito** [comment]
Same here.

```
victorgama:repo/ (master) $
branch   | master
position | up-to-date

/usr/local/lib/node_modules/gitgoodies/lib/gg.js:197
                if (status[4].split(' ')[0] === 'Untracked') {
                             ^
TypeError: Cannot read property 'split' of undefined
    at /usr/local/lib/node_modules/gitgoodies/lib/gg.js:197:18
    at ChildProcess.exithandler (child_process.js:707:7)
    at emitTwo (events.js:85:13)
    at ChildProcess.emit (events.js:153:7)
    at maybeClose (child_process.js:984:16)
    at Socket.<anonymous> (child_process.js:1153:11)
    at emitOne (events.js:75:13)
    at Socket.emit (events.js:150:7)
    at Pipe.close (net.js:457:12)

victorgama:repo/ (master) $ git --version
git version 2.3.2
victorgama:repo/ (master) $ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
victorgama:repo/ (master) $ echo $0
-zsh
```

**Comment by qw3rtman** [comment]
Rewrote the staging section of the status command from scratch. Update with `npm update -g gitgoodies`. Let me know if the issue is fixed. :smile:

**Comment by qw3rtman** [comment]
Alright, tested and working on my end. Let me know if it's fixed now.
