### ISSUE TITLE
gg l > Unexpected end of input error

### ISSUE THREAD

**Issue by ianwalter** [qw3rtman/gg#38]
```
ian$ gg l
undefined:5361
  "author": "<hidden>"

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /usr/local/lib/node_modules/gitgoodies/lib/gg.js:513:22
    at ChildProcess.exithandler (child_process.js:723:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at maybeClose (child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1057:5)
```

**Comment by jmooo** [comment]
:+1:

**Comment by gtors** [comment]
Similar problem
gg  version 0.6.4

```
[gts@gts prj]$ gg l
undefined:5374
  "date": "Tue Feb 10 

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /usr/lib/node_modules/gitgoodies/lib/gg.js:513:22
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

**Comment by qw3rtman** [comment]
Sadly, this Node.js version of Git Goodies will no longer be maintained. On the bright side, I have recently completed a version of [Git Goodies in Shell](https://github.com/qw3rtman/gg) with more features, more speed, and less bugs. I believe it solves this issue as well; if you could let me know for sure, that'd be great. :smile:
