### ISSUE TITLE
gg s handling of undefined fileds

### ISSUE THREAD

**Issue by martin-spa** [qw3rtman/gg#43]
I'm having a problem when using the `gg s` command:

```
D:\Test\test\docs>gg s
branch   | undefined

C:\Users\martin\AppData\Roaming\npm\node_modules\gitgoodies\lib\gg.js:279
    switch (status[1].split(' ')[3]) {
                      ^
TypeError: Cannot call method 'split' of undefined
    at C:\Users\martin\AppData\Roaming\npm\node_modules\gitgoodies\lib\gg.js:279:23
    at ChildProcess.exithandler (child_process.js:662:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

And here's the output from `git status`:

```
$ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        Main.txt

nothing added to commit but untracked files present (use "git add" to track)
```

So, the git repository is there (not related to #31 or #35).

gitgoodies@0.6.4

**Comment by qw3rtman** [comment]
Sadly, this Node.js version of Git Goodies will no longer be maintained. On the bright side, I have recently completed a version of [Git Goodies in Shell](https://github.com/qw3rtman/gg) with more features, more speed, and less bugs. I believe it solves this issue as well; if you could let me know for sure, that'd be great. :smile:
